### ISSUE TITLE
Miniplayer ist not affected by custom css

### ISSUE THREAD

**Issue by rathlinus** [Venipa/ytmdesktop2#135]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
That the custom css is also applied to the miniplayer

**Comment by Venipa** [comment]
just to be sure, the mini player is not made by youtube.
its made by myself, thats why the custom css is only injected into youtubes layout.
but i tagged this request as a feature request for now
![image](https://github.com/user-attachments/assets/84d440ee-8770-41e4-b1ea-496e366b345a)

**Comment by rathlinus** [comment]
Yeah, i know you guys made that, but it would still be cool, because it looks wired when in a smaller window on my screen. I will try to write some better css for that.
![grafik](https://github.com/user-attachments/assets/b32cad97-f72c-4ab8-b9f0-ed2e459df876)

**Comment by rathlinus** [comment]
I have tried compiling it, but iam not experienced enough with electron to fix this error when compiling, maybe you can help:

``` INFO  Launching Electron...

(node:24188) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'split')
    at eval (webpack://ytmdesktop2/./src/app/plugins/updateProvider.plugin.ts?:26:82)
    at ./src/app/plugins/updateProvider.plugin.ts (C:\Users\info\Downloads\ytmdesktop2-master\ytmdesktop2-master\dist_electron\index.js:11571:1)
    at __webpack_require__ (C:\Users\info\Downloads\ytmdesktop2-master\ytmdesktop2-master\dist_electron\index.js:14436:42)
    at webpackContext (webpack://ytmdesktop2/./src/app/plugins/_sync_nonrecursive_plugin.ts$/?:22:9)
    at Array.map (<anonymous>)
    at eval (webpack://ytmdesktop2/./src/app/utils/serviceCollection.ts?:13:14)
    at createPluginCollection (webpack://ytmdesktop2/./src/app/utils/serviceCollection.ts?:33:7)
    at __WEBPACK_DEFAULT_EXPORT__ (webpack://ytmdesktop2/./src/app/main.ts?:38:117)
    at eval (webpack://ytmdesktop2/./src/background.ts?:7:54)
    at ./src/background.ts (C:\Users\info\Downloads\ytmdesktop2-master\ytmdesktop2-master\dist_electron\index.js:11780:1)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:24188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[30148:0924/222700.001:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is
```

**Comment by Venipa** [comment]
dont forget to copy the .env.example to .env

**Comment by rathlinus** [comment]
yep, thanks 😅
