### ISSUE TITLE
Discord Rich Presence not working.

### ISSUE THREAD

**Issue by Jonybtw** [Venipa/ytmdesktop2#46]
### Operating system

 Microsoft Windows [Version 10.0.22621.963]

### YouTube Music Desktop App Version

v0.9.7 (latest)

### Bug description

Discord Rich Presence is not working.
![YouTube_Music_for_Desktop_9nWRKxG7pR](https://user-images.githubusercontent.com/84144569/209433650-2090d1c7-9691-46eb-837e-5c1ac180a935.png)
It shows as it's on but doesn't show up on profile on Discord.

**Comment by Venipa** [comment]
its working, its just an issue with discord's rpc server not immediately setting the presence, starting discord/ytmdesktop2 as admin should fix this

**Comment by BlackBirdTV** [comment]
Sorry I have to bring this back up, but it doesn't work for me.

**Operating System**

Fedora Linux 36

**YouTube Music Desktop App Version**

v0.9.7 (latest)

**Bug description**

Same as above.

Relevant log output

Here is a dump of the output, but I couldn't find anything that seems to have a connection to the issue.
```
[winston] Attempt to write logs with no transports, which can increase memory usage: {"label":"app","message":"Loaded Providers: api, app, customcss, discord, events, mediaController, mp, navigation, settings, startup, track, tray, update","level":"debug"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"label":"app","message":"Loaded Events: settingsProvider.change, track:change","level":"debug"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"update","level":"debug","label":"app"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"update","message":"Updater Cache: /home/luis/.cache","level":"debug","label":"app"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"settings","message":"/home/luis/.config/YouTube Music for Desktop/app-settings.json","level":"debug","label":"app"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"event/settingsProvider.change","message":"registered \"server\" event \"settingsProvider.change\"","level":"debug","label":"app"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"event/track:change","message":"registered \"server\" event \"track:change\"","level":"debug","label":"app"}
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Error: ENOENT, 512x512.35d33607.png not found in /tmp/.mount_YouTubYNluoG/resources/app.asar
    at createError (node:electron/js2c/asar_bundle:5:1255)
    at fsReadFileAsar (node:electron/js2c/asar_bundle:5:7706)
    at e.readFile (node:electron/js2c/asar_bundle:5:8838)
    at Function.<anonymous> (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3319315) {
  code: 'ENOENT',
  errno: -2
}
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "Bus name was not valid: 'org.mpris.MediaPlayer2.YouTube Music for Desktop'"', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.9.5/src/strings.rs:213:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"update","message":"Checking for update","level":"info","label":"app"}
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Failed to load image from path '/tmp/.mount_YouTubYNluoG/resources/app.asar/favicon.ico'
    at _.initializeTray (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3302051)
    at c.AfterInit (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3285514)
    at /tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3320301
    at Array.map (<anonymous>)
    at Object.exec (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3320273)
    at App.<anonymous> (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3324797)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: "Bus name was not valid: 'org.mpris.MediaPlayer2.YouTube Music for Desktop'"
    at new MediaServiceProvider (/tmp/.mount_YouTubYNluoG/resources/app.asar/node_modules/xosms/dist/binding.js:32:43)
    at $.AfterInit (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3273958)
    at /tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3320301
    at Array.map (<anonymous>)
    at Object.exec (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3320273)
    at App.<anonymous> (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3324797)
(node:23606) UnhandledPromiseRejectionWarning: Error: Failed to load image from path '/tmp/.mount_YouTubYNluoG/resources/app.asar/favicon.ico'
    at _.initializeTray (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3302051)
    at c.AfterInit (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3285514)
    at /tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3320301
    at Array.map (<anonymous>)
    at Object.exec (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3320273)
    at App.<anonymous> (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3324797)
(Use `youtube music for desktop --trace-warnings ...` to show where the warning was created)
(node:23606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23606) UnhandledPromiseRejectionWarning: Error: internal error in Neon module: called `Result::unwrap()` on an `Err` value: "Bus name was not valid: 'org.mpris.MediaPlayer2.YouTube Music for Desktop'"
    at new MediaServiceProvider (/tmp/.mount_YouTubYNluoG/resources/app.asar/node_modules/xosms/dist/binding.js:32:43)
    at $.AfterInit (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3273958)
    at /tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3320301
    at Array.map (<anonymous>)
    at Object.exec (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3320273)
    at App.<anonymous> (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:3324797)
(node:23606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"discord","level":"debug","label":"app","stack":"Error: Could not connect\n    at Socket.i (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:123463)\n    at Object.onceWrapper (node:events:642:26)\n    at Socket.emit (node:events:527:28)\n    at Socket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","message":"Could not connect"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"update","message":"Update for version 0.9.7 is not available (latest version: 0.9.7, downgrade is disallowed).","level":"info","label":"app"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"update","message":"No Update available","level":"error","label":"app"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"discord","level":"debug","label":"app","stack":"Error: Could not connect\n    at Socket.i (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:123463)\n    at Object.onceWrapper (node:events:642:26)\n    at Socket.emit (node:events:527:28)\n    at Socket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","message":"Could not connect"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"discord","level":"debug","label":"app","stack":"Error: Could not connect\n    at Socket.i (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:123463)\n    at Object.onceWrapper (node:events:642:26)\n    at Socket.emit (node:events:527:28)\n    at Socket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","message":"Could not connect"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"discord","level":"debug","label":"app","stack":"Error: Could not connect\n    at Socket.i (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:123463)\n    at Object.onceWrapper (node:events:642:26)\n    at Socket.emit (node:events:527:28)\n    at Socket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","message":"Could not connect"}
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"discord","level":"debug","label":"app","stack":"Error: Could not connect\n    at Socket.i (/tmp/.mount_YouTubYNluoG/resources/app.asar/index.js:2:123463)\n    at Object.onceWrapper (node:events:642:26)\n    at Socket.emit (node:events:527:28)\n    at Socket.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)","message":"Could not connect"}
[23651:0102/141602.576720:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[23651:0102/141602.580810:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[23651:0102/141602.583047:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
[winston] Attempt to write logs with no transports, which can increase memory usage: {"moduleName":"navigation","message":"isHome :: true, https://music.youtube.com/watch?v=zRHlMpJresQ&list=RDAMVMzRHlMpJresQ","level":"debug","label":"app"}
```

**Comment by Venipa** [comment]
> BlackBirdTV

log says its clearly not being able to connect to rpc, make sure you are running the desktop client, not the browser version

**Comment by BlackBirdTV** [comment]
@Venipa I am running discord desktop, maybe it's because i am running discord from snap?

**Comment by Venipa** [comment]
> @Venipa I am running discord desktop, maybe it's because i am running discord from snap?

yes you would need to manually install discord, snap runs the app in a container which wont allow ipc communication between processes afaik
