### ISSUE TITLE
Unable to run a local build on Linux

### ISSUE THREAD

**Issue by patrickwhelan99** [Venipa/ytmdesktop2#95]
### Operating system

Fedora Linux 38, Linux Kernel 6.7.6-100

### YouTube Music Desktop App Version

v0.10.11

### Bug description

Following the steps in the README I was able to build the app locally but couldn't run it.

Downloading the build from the releases works, but checking out the same commit locally and building gives errors when trying to run the application.

I would guess it's the libva error which means the app won't launch? 

Here's the two md5 hashes for the compiled appImages

Local build:
7fa9cafe2b67c012f459c3ba1d9b2d96

Released build:
2698b402024ee0430c6c0f7bc84b8c95

### Steps to reproduce

```
git clone https://github.com/Venipa/ytmdesktop2.git
git checkout v0.10.11
yarn
yarn build
dist_electron/YouTube\ Music\ for\ Desktop-0.10.11.AppImage
```

### Relevant log output

```shell
Building the App

yarn build
yarn run v1.22.21
$ vue-cli-service electron:build --mode development
 INFO  Bundling render process:
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme
All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠏  Building for development...[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.

⠋  Building for development...
🌼 daisyUI components 2.22.0  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[29], utilities
  

warn - The `darkMode` option in your Tailwind CSS configuration is set to `false`, which now behaves the same as `media`.
warn - Change `darkMode` to `media` or remove it entirely.
warn - https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration
⠧  Building for development...
🌼 daisyUI components 2.22.0  https://github.com/saadeghi/daisyui
  ✔︎ Including:  base, components, themes[29], utilities
  
⠋  Building for development...

 WARNING  Compiled with 1 warning                                                                                                                   20:45:49

[eslint] 
/home/paz/projects/gitClones/ytmdesktop2/src/components/SectionCard.vue
  17:7  warning  'props' is assigned a value but never used  @typescript-eslint/no-unused-vars

/home/paz/projects/gitClones/ytmdesktop2/src/views/mini-player/index.vue
  246:43  warning  'watch' is defined but never used        @typescript-eslint/no-unused-vars
  246:50  warning  'watchEffect' is defined but never used  @typescript-eslint/no-unused-vars

/home/paz/projects/gitClones/ytmdesktop2/src/views/youtube/toolbar-options.vue
  109:24  warning  'setMiniPlayer' is assigned a value but never used  @typescript-eslint/no-unused-vars

✖ 4 problems (0 errors, 4 warnings)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
  File                                                                            Size                                Gzipped

  dist_electron/bundled/js/chunk-vendors.js                                       838.53 KiB                          173.22 KiB
  dist_electron/bundled/js/src_views_mini-player_index_vue.js                     194.93 KiB                          21.07 KiB
  dist_electron/bundled/js/app.js                                                 126.81 KiB                          20.28 KiB
  dist_electron/bundled/js/src_views_youtube_toolbar_vue.js                       118.72 KiB                          12.48 KiB
  dist_electron/bundled/js/node_modules_core-js_modules_es_array_for-each_js-n    68.21 KiB                           10.92 KiB
  ode_modules_core-js_modules_es_array_slice-90d988.js
  dist_electron/bundled/js/src_utils_Ipc_ts.js                                    62.15 KiB                           10.15 KiB
  dist_electron/bundled/js/src_views_settings_index_vue.js                        41.48 KiB                           5.39 KiB
  dist_electron/bundled/js/src_components_SettingsCheckbox_vue.js                 36.76 KiB                           6.47 KiB
  dist_electron/bundled/js/src_views_youtube_loading_vue.js                       34.49 KiB                           3.20 KiB
  dist_electron/bundled/js/node_modules_vue_babel-preset-app_node_modules_babe    30.52 KiB                           5.57 KiB
  l_runtime_helpers_esm_asyncToGenerator_js--531dfc.js
  dist_electron/bundled/js/src_components_ControlBar_vue.js                       28.45 KiB                           2.93 KiB
  dist_electron/bundled/js/src_views_youtube_toolbar-mac_vue.js                   28.10 KiB                           3.32 KiB
  dist_electron/bundled/js/src_views_settings_about-settings_vue.js               27.76 KiB                           5.05 KiB
  dist_electron/bundled/js/src_views_settings_player-settings_vue.js              27.61 KiB                           3.34 KiB
  dist_electron/bundled/js/src_components_SettingsInput_vue.js                    26.10 KiB                           5.00 KiB
  dist_electron/bundled/js/src_views_settings_integration-settings_vue.js         23.74 KiB                           2.74 KiB
  dist_electron/bundled/js/src_views_settings_customcss-settings_vue.js           21.91 KiB                           2.35 KiB
  dist_electron/bundled/js/src_views_settings_generic-settings_vue.js             20.19 KiB                           3.57 KiB
  dist_electron/bundled/js/src_views_settings_discord-settings_vue.js             10.76 KiB                           1.70 KiB

  Images and other types of assets omitted.
  Build at: 2024-03-04T20:45:49.803Z - Hash: 2a8d36ba124484c0 - Time: 6720ms

 DONE  Build complete. The dist_electron/bundled directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
       
⠼  Bundling main process...

 WARNING  Compiled with 2 warnings                                                                                                                  20:45:53

 warning  in ./node_modules/keyv/src/index.js

Critical dependency: the request of a dependency is an expression

 warning  in ./src/app/plugins/discordProvider.plugin.ts

export 'TrackData' (imported as 'TrackData') was not found in '@/app/utils/trackData' (possible exports: discordEmbedFromTrack, parseMusicChannelById, parseMusicUrlById)

  File                              Size                                                       Gzipped

  dist_electron/bundled/index.js    9805.76 KiB                                                1721.17 KiB

  Images and other types of assets omitted.
  Build at: 2024-03-04T20:45:53.564Z - Hash: 00897d4a822850becbd6 - Time: 3489ms

⠧  Bundling preload files...

 DONE  Compiled successfully in 644ms                                                                                                               20:45:54

  File                                    Size                                                    Gzipped

  dist_electron/bundled/api.js            489.29 KiB                                              105.03 KiB
  dist_electron/bundled/preload-yt.js     207.76 KiB                                              27.80 KiB
  dist_electron/bundled/preload-api.js    192.20 KiB                                              24.57 KiB

  Images and other types of assets omitted.
  Build at: 2024-03-04T20:45:54.229Z - Hash: 486841e215a2a0107f47 - Time: 644ms

 INFO  Building app with electron-builder:
  • electron-builder  version=22.14.13 os=6.7.6-100.fc38.x86_64
  • description is missed in the package.json  appPackageFile=/home/paz/projects/gitClones/ytmdesktop2/dist_electron/bundled/package.json
  • writing effective config  file=dist_electron/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=bufferutil@4.0.6, keytar@7.9.0, utf-8-validate@5.0.9 platform=linux arch=x64
  • install prebuilt binary  name=keytar version=7.9.0 platform=linux arch=x64 napi=
  • rebuilding native dependency  name=bufferutil version=4.0.6
  • rebuilding native dependency  name=utf-8-validate version=5.0.9
  • packaging       platform=linux arch=x64 electron=20.3.9 appOutDir=dist_electron/linux-unpacked
  • building        target=AppImage arch=x64 file=dist_electron/YouTube Music for Desktop-0.10.11.AppImage
 DONE  Build complete!
Done in 19.09s.







Running the App

./YouTube\ Music\ for\ Desktop-0.10.11.AppImage

(node:148527) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'split')
    at eval (webpack://ytmdesktop2/./src/app/plugins/updateProvider.plugin.ts?:26:82)
    at ./src/app/plugins/updateProvider.plugin.ts (/tmp/.mount_YouTubhBn5xH/resources/app.asar/index.js:10166:1)
    at __webpack_require__ (/tmp/.mount_YouTubhBn5xH/resources/app.asar/index.js:13108:42)
    at webpackContext (webpack://ytmdesktop2/./src/app/plugins/_sync_nonrecursive_plugin.ts$/?:22:9)
    at Array.map (<anonymous>)
    at eval (webpack://ytmdesktop2/./src/app/utils/serviceCollection.ts?:13:14)
    at createPluginCollection (webpack://ytmdesktop2/./src/app/utils/serviceCollection.ts?:33:7)
    at __WEBPACK_DEFAULT_EXPORT__ (webpack://ytmdesktop2/./src/app/main.ts?:38:117)
    at eval (webpack://ytmdesktop2/./src/background.ts?:7:54)
    at ./src/background.ts (/tmp/.mount_YouTubhBn5xH/resources/app.asar/index.js:10375:1)
(Use `youtube music for desktop --trace-warnings ...` to show where the warning was created)
(node:148527) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

**Comment by patrickwhelan99** [comment]
That fixed it, thanks! :partying_face: :pray:
